/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;
/** 
 *
 * @author siana
 */
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

import Conexion.CreateConection;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

// Tu clase de conexión
import Conexion.CreateConection;
    
    
    public class Reportes1prueba extends javax.swing.JFrame {
    
        CreateConection conexionPostgres = new CreateConection();
        Connection con;
        
        
        
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reportes1prueba.class.getName());
    
    
    /**
     * Creates new form Reportes
     */
    private void agruparBotones() {
        ButtonGroup grupoReportes = new ButtonGroup();
        grupoReportes.add(RBEmpleados);
        grupoReportes.add(RBClientes);
        grupoReportes.add(RBProveedores);
        grupoReportes.add(RBProductos);
        grupoReportes.add(RBVentas);
    }
    
    public Reportes1prueba() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Reportes del Sistema");

        try {
            con = conexionPostgres.getConection();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de conexión: " + e.getMessage());
        }
    }

    private String obtenerRutaReporte() {
        if (RBEmpleados.isSelected()) return "/reportes/empleados.jasper";
        if (RBProveedores.isSelected()) return "/reportes/proveedores.jasper";
        if (RBProductos.isSelected()) return "/reportes/productos.jasper";
        if (RBClientes.isSelected()) return "/reportes/clientes.jasper";
        if (RBVentas.isSelected()) return "/reportes/ventasGenerales.jasper"; 
        return null;
    }
    private String obtenerNombreArchivo() {
        if (RBEmpleados.isSelected()) return "Reporte_Empleados";
        if (RBProveedores.isSelected()) return "Reporte_Proveedores";
        if (RBProductos.isSelected()) return "Reporte_Productos";
        if (RBClientes.isSelected()) return "Reporte_Clientes";
        if (RBVentas.isSelected()) return "Reporte_VentasGenerales";
        return "Reporte";
    }
    
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnPDF;
    private javax.swing.JRadioButton RBClientes;
    private javax.swing.JRadioButton RBEmpleados;
    private javax.swing.JRadioButton RBProductos;
    private javax.swing.JRadioButton RBProveedores;
    private javax.swing.JRadioButton RBVentas;
    private javax.swing.ButtonGroup buttonGroup1;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        RBProveedores = new javax.swing.JRadioButton();
        RBEmpleados = new javax.swing.JRadioButton();
        RBProductos = new javax.swing.JRadioButton();
        RBClientes = new javax.swing.JRadioButton();
        RBVentas = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        jLabel1.setText("REPORTES");

        btnReporte.setText("Ver reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnPDF.setText("Exportar PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBProveedores);
        RBProveedores.setText("Proveedores");
        RBProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBProveedoresActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBEmpleados);
        RBEmpleados.setText("Empleados");
        RBEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBEmpleadosActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBProductos);
        RBProductos.setText("Productos");
        RBProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBProductosActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBClientes);
        RBClientes.setText("Clientes");
        RBClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBClientesActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBVentas);
        RBVentas.setText("Ventas");
        RBVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBProveedores)
                    .addComponent(RBEmpleados)
                    .addComponent(RBProductos)
                    .addComponent(RBClientes)
                    .addComponent(RBVentas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(RBEmpleados)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RBProveedores)
                        .addGap(18, 18, 18)
                        .addComponent(RBProductos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReporte)
                        .addGap(34, 34, 34)
                        .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBClientes)
                .addGap(18, 18, 18)
                .addComponent(RBVentas)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
         try {
            String ruta = obtenerRutaReporte();
            if (ruta == null) {
                JOptionPane.showMessageDialog(this, "Seleccione un reporte antes de continuar.");
                return;
            }

            JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource(ruta));
            JasperPrint jprint = JasperFillManager.fillReport(reporte, new HashMap<>(), con);

            JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setTitle("Vista previa de reporte");
            viewer.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar el reporte:\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        try {
            String ruta = obtenerRutaReporte();
            if (ruta == null) {
                JOptionPane.showMessageDialog(this, "Seleccione un reporte antes de continuar.");
                return;
            }

            JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource(ruta));
            JasperPrint jprint = JasperFillManager.fillReport(reporte, new HashMap<>(), con);

            // Nombre del archivo
            String nombre = obtenerNombreArchivo();
            String destino = nombre + "_" + java.time.LocalDate.now() + ".pdf";

            JasperExportManager.exportReportToPdfFile(jprint, destino);
            JOptionPane.showMessageDialog(this, "PDF exportado correctamente:\n" + destino);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al exportar PDF:\n" + e.getMessage());
        }
    }

    }//GEN-LAST:event_btnPDFActionPerformed


    private void RBClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBClientesActionPerformed

    private void RBEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBEmpleadosActionPerformed

    private void RBProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBProveedoresActionPerformed

    private void RBProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBProductosActionPerformed

    private void RBVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reportes1prueba().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBClientes;
    private javax.swing.JRadioButton RBEmpleados;
    private javax.swing.JRadioButton RBProductos;
    private javax.swing.JRadioButton RBProveedores;
    private javax.swing.JRadioButton RBVentas;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnReporte;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
