/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import Conexion.CreateConection;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import java.io.InputStream;

// Librerías de JasperReports
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author danny
 */
public class ReportesEmpleados extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportesEmpleados.class.getName());

    /**
     * Creates new form Reportes_empleados
     */
    CreateConection conexionPostgres = new CreateConection();
Connection con;

public ReportesEmpleados() throws SQLException {
    initComponents();
    con = conexionPostgres.getConection();
    this.setLocationRelativeTo(null);
    this.setTitle("Reportes de Empleados");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGeneral = new javax.swing.JButton();
        btnActivos = new javax.swing.JButton();
        btnInactivos = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        btnGeneral.setText("Reporte general de Empleados");
        btnGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralActionPerformed(evt);
            }
        });

        btnActivos.setText("Ver Solo empleados Activos");
        btnActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivosActionPerformed(evt);
            }
        });

        btnInactivos.setText("Ver Solo Empleados Inactivos");
        btnInactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivosActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Anton SC", 2, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Reportes  Empleados");
        lblTitulo.setMaximumSize(new java.awt.Dimension(50, 50));
        lblTitulo.setMinimumSize(new java.awt.Dimension(50, 50));
        lblTitulo.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInactivos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGeneral))))
                .addGap(407, 407, 407))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActivos)
                .addGap(18, 18, 18)
                .addComponent(btnInactivos)
                .addGap(18, 18, 18)
                .addComponent(btnGeneral)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralActionPerformed
         try {
        String ruta = "/reportes/empleados.jasper";
        JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource(ruta));
        Map<String, Object> parametros = new HashMap<>();

        JasperPrint jprint = JasperFillManager.fillReport(reporte, parametros, con);

        JasperViewer viewer = new JasperViewer(jprint, false);
        viewer.setTitle("Reporte General de Empleados");
        viewer.setVisible(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al generar el reporte:\n" + e.getMessage());
    }
    }//GEN-LAST:event_btnGeneralActionPerformed

    private void btnActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivosActionPerformed
       try {
        // Carga el reporte de empleados activos
        InputStream path = getClass().getResourceAsStream("/reportes/empleadosActivos.jasper");
        
        if (path == null) {
            throw new RuntimeException("No se encontró el archivo empleadosActivos.jasper en /reportes/");
        }

        // Parámetros opcionales
        Map<String, Object> parametros = new HashMap<>();
        parametros.put("SUBREPORT_DIR", "/reportes/");

        JasperPrint print = JasperFillManager.fillReport(path, parametros, con);
        JasperViewer.viewReport(print, false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al generar el reporte de empleados activos:\n" + e.getMessage());
    }
    }//GEN-LAST:event_btnActivosActionPerformed

    private void btnInactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivosActionPerformed
        try {
        // Carga el reporte de empleados inactivos
        InputStream path = getClass().getResourceAsStream("/reportes/empleadosInactivos.jasper");

        if (path == null) {
            throw new RuntimeException("No se encontró el archivo empleadosInactivos.jasper en /reportes/");
        }

        Map<String, Object> parametros = new HashMap<>();
        parametros.put("SUBREPORT_DIR", "/reportes/");

        JasperPrint print = JasperFillManager.fillReport(path, parametros, con);
        JasperViewer.viewReport(print, false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al generar el reporte de empleados inactivos:\n" + e.getMessage());
    }
    }//GEN-LAST:event_btnInactivosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        try {
            ReportesEmpleados ventana = new ReportesEmpleados();
            ventana.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, 
                "Error al iniciar la ventana de reportes:\n" + ex.getMessage(),
                "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivos;
    private javax.swing.JButton btnGeneral;
    private javax.swing.JButton btnInactivos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
