/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import Conexion.CreateConection;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ButtonGroup;

import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.DefaultJasperReportsContext;
import javax.swing.JOptionPane;

public class Reportes extends javax.swing.JFrame {

    private Connection con;

    public Reportes() {
        initComponents();
        setLocationRelativeTo(null);
        agruparRB();

        // Conexión
        try {
            CreateConection cx = new CreateConection();
            con = cx.getConection();
            System.out.println("Conexión establecida");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al conectar con la base de datos:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void agruparRB() {
        ButtonGroup g = new ButtonGroup();
        g.add(RBEmpleados);
        g.add(RBProveedores);
        g.add(RBClientes);
        g.add(RBProductos);
        g.add(RBVentasGenerales);
        g.add(RBVentasProductos);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        RBProveedores = new javax.swing.JRadioButton();
        RBEmpleados = new javax.swing.JRadioButton();
        RBProductos = new javax.swing.JRadioButton();
        RBClientes = new javax.swing.JRadioButton();
        RBVentasGenerales = new javax.swing.JRadioButton();
        btnSalir = new javax.swing.JButton();
        RBVentasProductos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        jLabel1.setText("REPORTES");

        btnReporte.setText("Ver reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnPDF.setText("Imprimir Reporte");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        RBProveedores.setBackground(new java.awt.Color(0, 153, 153));
        buttonGroup1.add(RBProveedores);
        RBProveedores.setText("Proveedores");
        RBProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBProveedoresActionPerformed(evt);
            }
        });

        RBEmpleados.setBackground(new java.awt.Color(0, 153, 153));
        buttonGroup1.add(RBEmpleados);
        RBEmpleados.setText("Empleados");
        RBEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBEmpleadosActionPerformed(evt);
            }
        });

        RBProductos.setBackground(new java.awt.Color(0, 153, 153));
        buttonGroup1.add(RBProductos);
        RBProductos.setText("Productos");
        RBProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBProductosActionPerformed(evt);
            }
        });

        RBClientes.setBackground(new java.awt.Color(0, 153, 153));
        buttonGroup1.add(RBClientes);
        RBClientes.setText("Clientes");
        RBClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBClientesActionPerformed(evt);
            }
        });

        RBVentasGenerales.setBackground(new java.awt.Color(0, 153, 153));
        buttonGroup1.add(RBVentasGenerales);
        RBVentasGenerales.setText("Ventas Generales");
        RBVentasGenerales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBVentasGeneralesActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        RBVentasProductos.setBackground(new java.awt.Color(0, 153, 153));
        buttonGroup1.add(RBVentasProductos);
        RBVentasProductos.setText("Ventas por Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RBProveedores)
                                    .addComponent(RBEmpleados)
                                    .addComponent(RBProductos)
                                    .addComponent(RBClientes)
                                    .addComponent(RBVentasGenerales))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(RBVentasProductos)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(RBEmpleados)
                        .addGap(18, 18, 18)
                        .addComponent(RBProveedores)
                        .addGap(18, 18, 18)
                        .addComponent(RBProductos)
                        .addGap(18, 18, 18)
                        .addComponent(RBClientes)
                        .addGap(18, 18, 18)
                        .addComponent(RBVentasGenerales)
                        .addGap(18, 18, 18)
                        .addComponent(RBVentasProductos)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReporte)
                        .addGap(18, 18, 18)
                        .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)
                        .addGap(81, 81, 81))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        String ruta = obtenerRutaReporte();
    if (ruta == null) {
        JOptionPane.showMessageDialog(this,
            "Seleccione un reporte antes de continuar.",
            "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        Map<String, Object> params = new HashMap<>();
        JasperPrint print = JasperFillManager.fillReport(ruta, params, con);
        JasperViewer.viewReport(print, false);
    } catch (JRException ex) {
        JOptionPane.showMessageDialog(this,
            "Error al visualizar el reporte:\n" + ex.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        String ruta = obtenerRutaReporte();
    if (ruta == null) {
        JOptionPane.showMessageDialog(this,
            "Seleccione un reporte antes de imprimir.",
            "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        JasperPrint print = JasperFillManager.fillReport(ruta, null, con);
        JasperPrintManager.getInstance(DefaultJasperReportsContext.getInstance())
                .print(print, true);
        JOptionPane.showMessageDialog(this,
            "El reporte se envió correctamente a la impresora o PDF virtual.",
            "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (JRException ex) {
        JOptionPane.showMessageDialog(this,
            "Error al imprimir el reporte:\n" + ex.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnPDFActionPerformed


    private void RBClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBClientesActionPerformed

    private void RBEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBEmpleadosActionPerformed

    private void RBProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBProveedoresActionPerformed

    private void RBProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBProductosActionPerformed

    private void RBVentasGeneralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBVentasGeneralesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBVentasGeneralesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    private String obtenerRutaReporte() {
    String rutaBase = "src/reportes/";

    if (RBEmpleados.isSelected()) {
        return rutaBase + "empleados.jasper";
    } else if (RBProveedores.isSelected()) {
        return rutaBase + "proveedores.jasper";
    } else if (RBClientes.isSelected()) {
        return rutaBase + "clientes.jasper";
    } else if (RBProductos.isSelected()) {
        return rutaBase + "productos.jasper";
    } else if (RBVentasGenerales.isSelected()) {
        return rutaBase + "ventasGenerales.jasper";
    } else if (RBVentasProductos.isSelected()) {
        return rutaBase + "ventasProductos.jasper";
    }

    return null;
}



    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> new Reportes().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBClientes;
    private javax.swing.JRadioButton RBEmpleados;
    private javax.swing.JRadioButton RBProductos;
    private javax.swing.JRadioButton RBProveedores;
    private javax.swing.JRadioButton RBVentasGenerales;
    private javax.swing.JRadioButton RBVentasProductos;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
